// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package server

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// CheckResponse defines model for CheckResponse.
type CheckResponse struct {
	Status     HealthStatus `json:"status"`
	Message    string       `json:"message"`
	DurationMS int          `json:"duration_ms"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status       HealthStatus             `json:"status"`
	Dependencies map[string]CheckResponse `json:"dependencies"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string
